mongodb:
  architecture: replicaset
  useStatefulSet: true
  replicaCount: 3
  auth:
    enabled: true
    rootPassword: milliger
    replicaSetKey: milliger

persistence:
  enabled: true
  size: 150Mi
  storageClass: standard  # optional, remove or set to "-" if you don't want to specify a storage class

