apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-conf
data:
  MONGODB_URI: "mongodb://root:milliger@crm-mongodb-0.crm-mongodb-headless.default.svc.cluster.local:27017,crm-mongodb-1.crm-mongodb-headless.default.svc.cluster.local:27017,crm-mongodb-2.crm-mongodb-headless.default.svc.cluster.local:27017/test?authSource=admin"
  # MONGODB_URI: "mongodb://root:milliger@mongo-0.mongodb.default.svc.cluster.local:27017,mongo-1.mongodb.default.svc.cluster.local:27017,mongo-2.mongodb.default.svc.cluster.local:27017/test"
  PERSISTENCE: "true"
  LOG_LEVEL: "info"
