apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appSvc }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
